### ISSUE TITLE
Arc-Dark

### ISSUE THREAD

**Issue by brontosaurusrex** [dglava/arc-openbox#1]
A try at Arc-Dark openbox part;
https://github.com/brontosaurusrex/postbang/tree/master/.themes/Arc-Dark/openbox-3

**Comment by dglava** [comment]
Thank you for reminding me to add a dark theme.
However, I didn't use yours, since I saw that you added more than just color changes (altered alignment, border and padding). The colors also seem different from the original Arc theme's CSS files.

Anyway, 3e41d9bf6bd70feb21ce8e443633a3566735d8c1 added a dark theme.
