### ISSUE TITLE
Blue Color Not Correct

### ISSUE THREAD

**Issue by ghost** [dglava/arc-openbox#7]
Hi,

Thanks for making this for ARC, but either my eyes are playing tricks on me, or the color is not correct.

I see that you are using the same number that the theme uses, but for some reason Openbox does no display the blue the same, odd...

The shade looks brighter to me...

Also I used the Numix Flatstudio theme to make this into Arc style like, and I darkened the text a little, comparing it side by side with the look that I saw in SpaceFM.

Have a look and play and tell me what you think?

```The HIGHLIGHTED text below needs to have the # comment placed in the front to comment out...```

```Name: Arc Openbox theme```

```Menu```
menu.border.color: #ecedee
menu.border.width: 4
menu.title.bg: flat solid
menu.title.bg.color: #dbdfe3
menu.title.text.color: #5c616c
menu.title.text.justify: center

menu.items.bg: flat solid
menu.items.bg.color: #f5f6f7
menu.items.text.color: #84888f
menu.items.disabled.text.color: #aeb0b6

menu.items.active.bg: flat solid
menu.items.active.bg.color: #447fc9
menu.items.active.bg.colorTo: #447fc9
menu.items.active.text.color: #ffffff

menu.separator.color: #ECEDEE
menu.separator.width: 1
menu.separator.padding.width: 4
menu.separator.padding.height: 4

```Active window```
window.active.border.color: #ECEDEE

window.active.title.bg: flat solid
window.active.title.bg.color: #ECEDEE
window.active.title.separator.color: #ECEDEE
window.active.text.justify: center

window.active.label.bg: parentrelative
window.active.label.text.color: #6A6B6C

window.active.handle.bg: flat solid
window.active.handle.bg.color: #4FC0E8

window.active.grip.bg: flat solid
window.active.grip.bg.color: #4FC0E8

window.active.button.unpressed.bg: flat solid
window.active.button.unpressed.bg.color: #EA7878
window.active.button.unpressed.image.color: #ffffff

window.active.button.pressed.bg: flat solid
window.active.button.pressed.bg.color: #EA7878
window.active.button.pressed.image.color: #000000

window.active.button.disabled.bg: flat solid
window.active.button.disabled.bg.color: #CD9999
window.active.button.disabled.image.color: #ffffff

window.active.button.hover.bg: flat solid
window.active.button.hover.bg.color: #EA7878
window.active.button.hover.image.color: #ffffff

window.active.button.toggled.bg: flat solid
window.active.button.toggled.bg.color: #EA7878
window.active.button.toggled.image.color: #ffffff

window.active.button.toggled.unpressed.bg: flat solid
window.active.button.toggled.unpressed.bg.color: #EA7878
window.active.button.toggled.unpressed.image.color: #ffffff

window.active.button.toggled.pressed.bg: flat solid
window.active.button.toggled.pressed.bg.color: #EA7878
window.active.button.toggled.pressed.image.color: #000000
window.active.button.toggled.hover.image.color: #ffffff

```Inactive window```
window.inactive.border.color: #ECEDEE

window.inactive.title.bg: flat solid
window.inactive.title.bg.color: #ECEDEE
window.inactive.title.separator.color: #ECEDEE
window.inactive.text.justify: center

window.inactive.label.bg: parentrelative
window.inactive.label.text.color: #AAAEB2

window.inactive.handle.bg: flat solid
window.inactive.handle.bg.color: #F1F2F6

window.inactive.grip.bg: flat solid
window.inactive.grip.bg.color: #F1F2F6

window.inactive.button.unpressed.bg: flat solid
window.inactive.button.unpressed.bg.color: #BCBEC0
window.inactive.button.unpressed.image.color: #ffffff

window.inactive.button.pressed.bg: flat solid
window.inactive.button.pressed.bg.color: #BCBEC0
window.inactive.button.pressed.image.color: #000000

window.inactive.button.disabled.bg: flat solid
window.inactive.button.disabled.bg.color: #D2D4D6
window.inactive.button.disabled.image.color: #ffffff

window.inactive.button.hover.bg: flat solid
window.inactive.button.hover.bg.color: #BCBEC0
window.inactive.button.hover.image.color: #ffffff

window.inactive.button.toggled.bg: flat solid
window.inactive.button.toggled.bg.color: #BCBEC0
window.inactive.button.toggled.image.color: #ffffff
window.inactive.button.toggled.unpressed.bg: flat solid
window.inactive.button.toggled.unpressed.bg.color: #BCBEC0
window.inactive.button.toggled.unpressed.image.color: #ffffff

window.inactive.button.toggled.pressed.bg: flat solid
window.inactive.button.toggled.pressed.bg.color: #BCBEC0
window.inactive.button.toggled.pressed.image.color: #000000
window.inactive.button.toggled.hover.bg: flat solid
window.inactive.button.toggled.hover.image.color: #ffffff

```OSD```
osd.border.width: 2
osd.border.color: #ECEDEE

osd.bg: flat solid
osd.bg.color: #EEEEEE
osd.bg.colorTo: #EEEEEE
osd.label.bg: flat solid
osd.label.bg.color: #ECEDEE
osd.label.text.color: #6A6B6C

osd.hilight.bg: flat solid
osd.hilight.bg.color: #447fc9

osd.unhilight.bg: flat solid
osd.unhilight.bg.color: #ffffff

```Fonts```
window.active.label.text.font:shadow=n
window.inactive.label.text.font:shadow=n
menu.items.font:shadow=n
menu.title.text.font:shadow=n

```Everything else```
border.width: 2
padding.width: 4
padding.height: 4
window.handle.width: 0
window.client.padding.width: 0
window.label.text.justify: center

**Comment by ghost** [comment]
Instead of editing the original post, I forgot to mention, no offense to your work, it's nice, but I think the flat theme look, that has some border color looks a bit nicer, if you can see some of the colors are off, compared to Arc, maybe you can see some room for improvement...

Thanks

**Comment by dglava** [comment]
I just compared the blue highlight colors by using the color picker from GIMP inside a screenshot. They are identical and use the color #5294E2. See line ![4273](https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.20/gtk.css#L4273) from the Arc theme's CSS file to verify that it's using the mentioned color.

Screenshots of the comparison.
https://s1.postimg.org/7mxiv83ob3/stari1.png
https://s1.postimg.org/8iu0aofa73/stari2.png


If your highlight colors are off, check if you are using some transparent version of the Arc theme whose elements might blend with your background and mess with the actual, displayed color. You might also perceive the colors differently because the surrounding colors affect your perception of them.

The theme you posted doesn't look like the Arc theme from this repository. Is that your modified Numix Flatstudio theme? I don't think I want to apply the changes to this theme.

I'd like the colors in this theme to be the same used by the Arc GTK theme. I'll update this theme if someone spots issues where the colors are wrong compared to the Arc GTK theme. Since I stopped using this Openbox theme, there might actually already be some inconsistencies compared to the Arc GTK theme. But your issue seems to be related to something on your end.

**Comment by ghost** [comment]
Hi,

I'm not disagreeing that you are not using the same number.

Sorry my mistake for not mentioning SpaceFM.

The blue color on the Openbox menu is lighter in color then the color of blue that SpaceFM 1.0.4 represents, which is darker.

Have a look at the attached screen shot, and tell me if the color blue on the right that is in SpaceFM doesn't appear darker to you? It looks darker to me, and I don't get why SpaceFM doesn't render the color the same.

Hmm
![arc](https://user-images.githubusercontent.com/25046798/31572081-46d5b4b2-b08d-11e7-9828-080b763c1603.jpg)

**Comment by dglava** [comment]
I have just tested it with SpaceFM. It seems to be related to the GTK2 version of SpaceFM.

[SpaceFM compiled with GTK3](https://s1.postimg.org/2gjmby4xb3/2017-10-14-090208_1280x1024_scrot.png) uses the proper colours.
[SpaceFM compiled with GTK2](https://s1.postimg.org/2y9o0j8nrj/2017-10-14-090901_1280x1024_scrot.png) uses a different highlight colour, #4084d5, that I cannot find in neither Arc's nor in SpaceFM's source.

To rule out other GTK2 programs, I checked it with [Geany](https://s1.postimg.org/1rdldr5yjz/2017-10-14-094036_1280x800_scrot.png) and [LXappearance](https://s1.postimg.org/25k14mewkf/2017-10-14-094350_1280x800_scrot.png) and they both use the proper Arc highlight colour, #5294E2.

You should ask on the SpaceFM bug tracker for clarification on where the colour could be coming from, since it seems to be isolated to SpaceFM only.

Also, you should consider posting images in uncompressed formats in cases like these, PNG for example, because JPEG compression messes up some colours (your blue is slightly off from the blue I got in my screenshot).

**Comment by dglava** [comment]
I guess I'll close this as solved then.
